openapi: 3.0.0
info:
  version: '1.0'
  title: "EventManager"
  description: API per gestire eventi.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /EventiPubblici/{IDevento}:
    description: >-
    get:
      description: >-
        Ottieni informazioni riguardanti un evento pubblico specificandone l'ID.
      summary: >-
        Visualizza informazioni evento pubblico.
      parameters:
      - name: IDevento
        in: path
        description: >-
          ID dell'evento pubblico che si intende visualizzare.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: >-
            Elenco informazioni evento pubblico.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventoPubblico'
            example:
        '404':
          description: >-
            Non esiste alcun evento pubblico associato all'ID specificato.
  /EventiPersonali/{IDevento}:
    description: >-
    get:
      description: >-
        Ottieni informazioni riguardanti un evento personale specificandone l'ID.
      summary: >-
        Visualizza informazioni evento personale.
      parameters:
      - name: IDevento
        in: path
        description: >-
          ID dell'evento personale che si intende visualizzare.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: >-
            Elenco informazioni evento personale.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventoPersonale'
            example:
        '404':
          description: >-
            Non esiste alcun evento personale associato all'ID specificato.
components:
  schemas:
    EventID:
      type: string
    EventoPubblico:
    EventoPersonale:
