openapi: 3.0.0
info:
  version: '1.0'
  title: "EventManager"
  description: API per gestire eventi.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /EventiPubblici:
    post:
      description: Inviare le info per creare un nuovo evento pubblico.
      summary: Crea un nuovo evento pubblico
      parameters:
      - name: x-access-token
        in: header
        description: Token d'autenticazione
        required: true
      requestBody:
        description: Vengono indicati quali siano i dati per la programmazione di un certo evento pubblico
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicEvent'
      responses:
        '201':
          description: 'Evento pubblico creato. link alla locazione del evento pubblico'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'evento pubblico nuovo creato.
        '500':
          description: Errore al'interno del server (probabilmente riguardante il DB)
          content:
            application/json:
              schema:
                type: string
                description: "messaggio d'errore"
        '403':
          description: Non permessa l'operazione dal server (probabilmente perchè l'organizzatore ha già creato quell'evento)
          content:
            application/json:
              schema:
                type: string
                description: "messaggio d'errore"

  /EventiPersonali:
    post:
      description: Inviare le info per creare un nuovo evento personale.
      summary: Crea un nuovo evento pubblico
      parameters:
      - name: x-access-token
        in: header
        description: Token d'autenticazione
        required: true
      requestBody:
        description: Vengono indicati quali siano i dati per la programmazione di un certo evento personale
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalEvent'
      responses:
        '201':
          description: 'Evento pubblico creato. link alla locazione del evento pubblico'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'evento personale nuovo creato.
        '500':
          description: Errore al'interno del server (probabilmente riguardante il DB)
          content:
            application/json:
              schema:
                type: string
                description: "messaggio d'errore"
          
components:
  schemas:
    PublicEvent:
      description: Oggetto dell'evento personale
      type: object
      required:
      - data
      - ora
      - durata
      - maxPers
      - categoria
      - nomeAtt
      - luogoEv
      properties:
        data:
          type: string
          format: date
          description: 'Data dell''evento o lista date dell''evento'
        ora:
          type: string
          description: 'Ora d''inizio dell''evento'
        durata:
          type: number
          description: 'Durata dell''evento'
        maxPers:
          type: integer
          description: 'Numero massimo delle persone'
        categoria: 
          type: string
          description: 'Categoria dell''evento'
        nomeAtt:
          type: string
          description: 'Nome dell''Evento'
        luogoEv:
          type: object
          properties:
            indirizzo:
              type: string
              description: 'Inidirizzo dell''Evento'
            citta:
              type: string
              description: 'Città dell''Evento'
            
    PersonalEvent:
      description: Oggetto dell'evento personale
      type: object
      required:
      - data
      - ora
      - durata
      - categoria
      - nomeAtt
      properties:
        data:
          type: string
          format: date
          description: 'Data dell''evento'
        ora:
          type: string
          description: 'Ora dell''evento'
        durata:
          type: number
          description: 'Durata dell''evento'
        categoria: 
          type: string
          description: 'Categoria dell''evento'
        nomeAtt:
          type: string
          description: 'Nome dell''Evento'
        luogoEv:
          type: object
          properties:
            indirizzo:
              type: string
              description: 'Inidirizzo dell''Evento'
            citta:
              type: string
              description: 'Città dell''Evento'
