openapi: 3.0.0
info:
  version: '1.0'
  title: "EventManager"
  description: API per gestire eventi.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /creazioneEvento/pubblico:
    post:
      description: 'Inviare le info per creare un nuovo evento pubblico.'
      summary: Crea un nuovo evento pubblico
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicEvent'
      responses:
        '201':
          description: 'Evento pubblico creato. link alla locazione della risorsa'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'evento pubblico nuovo creato.

  /creazioneEvento/personale:
    post:
      description: 
        Crea un nuovo evento.
      summary: Crea un nuovo evento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalEvent'
      responses:
        '201':
          description: 'Evento personale creato. link alla locazione del evento'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'evento personale nuovo creato.
  
  /listaEventi:
    get:
      description: >-
        Ottieni la lista di eventi.
      summary: Visualizza gli eventi
      responses:
        '200':
          description: 'Lista di eventi'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventsList'

  /informazioniEvento/pubblico:
    get:
      description: >-
        Ottieni informazioni evento pubblico.
      summary: Visualizza informazioni evento pubblico
      responses:
        '200':
          description: 'Elenco informazioni evento pubblico'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicEvent'

  /informazioniEvento/personale:
    get:
      description: >-
        Ottieni informazioni evento personale.
      summary: Visualizza informazioni evento personale
      responses:
        '200':
          description: 'Elenco informazioni evento personale'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonalEvent'

components:
  schemas:
    PublicEvent:
    PersonalEvent:
    EventsList:
      type: object
      required:
        - list
      properties:
        list:
          type: array
          description: 'La lista di eventi in formato JSON'
