openapi: 3.0.0
info:
  version: '1.0'
  title: "EventManager"
  description: API per gestire eventi.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost


paths:
  /EventiPubblici/{idEvento}/Iscrizioni:
     post:
      description: Si richiede secondo un certo id dell'evento pubblico, la creazione dell'iscrizione per quell'evento da parte del utente corrente (indicato con il token)
      summary: Iscrizione ad un evento
      parameters:
      - name: Idevento
        in: path
        description: id dell'evento a cui si vuole iscrivere
        required: true
        schema:
          type: string
      - name: x-access-token
        in: header
        description: token to be passed as a header
        required: true
      responses:
        '201':
          description: 'Iscrizione all"evento. link all"evento'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'indirizzo dell'iscrizione a cui l'utente corrente si è iscritto.
              
              
                
        '403':
          description: 'il server ha deciso di non creare la risorsa'

        '400':
          description: 'Richiesta non capita dal server causa sintassi errata'

  /EventiPersonali/{idEvento}/Iscrizioni:
     post:
      description: Si richiede secondo un certo id dell'evento personale, la creazione dell'iscrizione per quell'evento da parte del utente corrente (indicato con il token)
      summary: Iscrizione ad un evento
      parameters:
      - name: Idevento
        in: path
        description: id dell'evento personale a cui si vuole iscrivere
        required: true
        schema:
          type: string
      - name: x-access-token
        in: header
        description: token di autenticazione dell'utente
        required: true
      responses:
        '201':
          description: 'Iscrizione all"evento personale. link all"evento'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'indirizzo dell'iscrizione a cui l'utente corrente si è iscritto.
              
              
                
        '403':
          description: 'il server ha deciso di non creare la risorsa, per motivi che possono essrer'

        '400':
          description: 'Richiesta non capita dal server causa sintassi errata'









